// <auto-generated />
namespace TangTinhCac.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TKC_v3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TKC_v3));
        
        string IMigrationMetadata.Id
        {
            get { return "202001021602452_TKC_v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
